### ISSUE TITLE
Submitting binary blobs into the repo

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/gcp-service-broker#104]
This repo does not appear have that much code, but it's quite heavy-weight:

```bash
% git clone https://github.com/GoogleCloudPlatform/gcp-service-broker.git
% cd gcp-service-broker
% du -shc
925M	.
925M	total
```

This appears to be because release artifacts are checked in as-is into the source repo. Is there a requirement for why this needs to be done? GitHub provides a [releases feature](https://github.com/GoogleCloudPlatform/gcp-service-broker/releases) that appears to be unused in this project, which lets you tag revisions with versions, and it automatically produces a .zip and .tar.gz version of the repo at the time of the tag, and you can also upload arbitrary binary blobs, such as build artifacts, to complete your release.

Alternatively, consider using the appropriate language-specific repositories (e.g., PyPI for Python, RubyGems for Ruby, Maven for Java, etc.). If none of those work, you can also create a separate repo to hold the released binaries, though one might argue that version control isn't very appropriate for large binary files, since you can't actually diff them, and you wouldn't edit them directly anyway, other than to replace them entirely. Another idea, if nothing else suffices, but you need a stable URL for your release artifacts, is to use a hosting service such as Google Cloud Storage to house your releases.

What do you think?

**Comment by ccemeraldeyes** [comment]
This is in progress on the concourse branch. It's de-prioritized over feature work for the moment, but should be completed soon.
