### ISSUE TITLE
Unable to deploy service broker in PWS w/ space-scope

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/gcp-service-broker#124]
GCP service broker fails to deploy in PWS with --space-scope registration.

It appears that the service ID, and service name may need to be globally unique - but not quite sure. Will it be possible to deploy a GCP service brokers in different spaces?

**Comment by ccemeraldeyes** [comment]
If you're deploying the service broker as an application and you wan to space-scope it, yes, you'll need to generate new service GUIDs and service names and update the manifest.yml
