### ISSUE TITLE
modify cloudsql supplied credentials to make use of proxy libraries

### ISSUE THREAD

**Issue by ccemeraldeyes** [GoogleCloudPlatform/gcp-service-broker#135]
Currently cloudsql returns a username, pw, and ssl certs for auth. This decision was made because the only known alternative at the time was to install a proxy service on each VM needing to connect to CloudSQL, which seemed like too much overhead. However, [Java and Go have proxy libraries](https://cloud.google.com/sql/docs/mysql/external-connection-methods?hl=en_US) that can be used with a service account and connection details (instance region in addition to what's provided now) instead.

**Comment by ccemeraldeyes** [comment]
Implementation options:

* always create both sets of creds and return both
* accept a custom parameter (e.g. `cred_type`)
* ???

**Comment by mgoddard-pivotal** [comment]
To me, it's probably okay to just have `VCAP_SERVICES` contain all of it, so you don't need the `cred_type` parameter.  Folks can just ignore whichever elements they don't need.

**Comment by mgoddard-pivotal** [comment]
Here's a simple Spring Boot app which might help illustrate what a CloudSQL binding ought to provide via its `VCAP_SERVICES` (note here the need to also bind to Storage to get the `PrivateKeyData` needed for using the default credentials, and also how the `instanceConnectionName` must be constructed from three chunks of data, one of which isn't yet available via any binding):

  https://github.com/mgoddard-pivotal/gcp-cloudsql-boot

**Comment by mkjelland** [comment]
@mgoddard-pivotal that sample app is really helpful, thank you! I'm looking into this now.
