### ISSUE TITLE
Add Cloud Datastore

### ISSUE THREAD

**Issue by mgoddard-pivotal** [GoogleCloudPlatform/gcp-service-broker#137]
Datastore seems like a nice idea to have.  I haven't had any requests for it, but since it appears to resemble Bigtable, but doesn't require you to allocate a minimum of three nodes, it'd be quite a bit more economical.

**Comment by athieriot** [comment]
Hello ! We are looking at using Google Datastore from CloudFoundry applications and that feature would be very valuable.

**Comment by sinsir** [comment]
+1

This would be a great addition
