### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by jamesmasters2** [GoogleCloudPlatform/gcp-service-broker#198]
I am trying to get the service broker to work from behind a corporate authenticated proxy. I have tried setting http_proxy and https_proxy (with auth), but that doesn't seem to be working.

**Comment by mkjelland** [comment]
@jamesmasters2 What isn't working? Are you getting an error when installing the service broker, or when attempting to create a service?

**Comment by jamesmasters2** [comment]
Thanks for your response. I'm able to add http_proxy and https_proxy environment variables to the deployed service broker, but they only seem to work against an unauthenticated squid instance. When I use credentials so the calls can get out of our authenticated corporate proxy to get to Google the calls fail (eg. Http://user:pass@proxy.com:3128)

**Comment by jamesmasters2** [comment]
And to your question, create-service calls fail

**Comment by mkjelland** [comment]
@jamesmasters2 I believe we'll have to implement the support for those 2 environment variables (http_proxy and https_proxy) into the service broker app for this to work. Right now the buildpack for the app will use the proxy, but the app itself is not using those fields. I'll take a look at this next week and keep you posted with what I find out.

**Comment by jamesmasters2** [comment]
Thank you @mkjelland

**Comment by mkjelland** [comment]
Hey jamesmasters2! I was able to set up an authenticated squid instance and use the service broker by setting the http_proxy and https_proxy environment variables on the service broker app (in the form http://user:password@proxy.com). How did you set up auth in the squid settings? I used the basic_ncsa_auth program when testing, but it would help if I used the same setup that you have.

**Comment by jamesmasters2** [comment]
Thanks for testing that out, @mkjelland. I can't explain it, but now it's working for me? I'll continue to test further to be sure. Thanks again!

**Comment by mkjelland** [comment]
That's great @jamesmasters2! I'll close this for now, but please reopen if you start seeing the issue again :)
