### ISSUE TITLE
gcp-sb 3.6.0 Tile Error on Cloud SQL 2nd Generation MySQL Instances

### ISSUE THREAD

**Issue by Pivotal-Jayson-Hairston** [GoogleCloudPlatform/gcp-service-broker#199]
I am getting the below errors when binding a cloud SQL Instance that uses a 2nd Generation instance:

These Errors happen when there is a plan configured with
"Tier/Machine Type" = `db-n1-standard-1`
ie. a value from https://cloud.google.com/sql/pricing#2nd-gen-instance-pricing

However, This does not happen when my plan had the value:
"Tier/Machine Type" = `D2`
ie. a value from a Gen I instance: https://cloud.google.com/sql/pricing#packages

---

Service Broker logs Errors:
"PUT /v2/service_instances/GUID/service_bindings/GUID HTTP/1.1" 502

Followed up with:
"DELETE /v2/service_instances/GUID/service_bindings/GUID?plan_id=GUID&service_id=GUID HTTP/1.1" 500

[APP/PROC/WEB/0] [ERR] {"timestamp":"1516987228.219666481","source":"my-service-broker","message":"my-service-broker.unbind.unknown-error","log_level":2,"data":{"binding-id":"GUID","error":"Error deleting ssl cert: googleapi: Error 403: Operation failed because another operation was already in progress., operationInProgress","instance-id":"GUID","session":"85"}}

---

CF CLI Error:
$ `cf bs sb-test sql-test -c '{"role": "cloudsql.admin"}'`
```
Binding service sql-test to app sb-test in org test / space gcp-tests as admin...
Error unmarshalling the following into a cloud controller error:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```
---

**Comment by mkjelland** [comment]
@Pivotal-Jayson-Hairston Does this happen consistently? Or is it happening when you run 2 bind/unbind operations back to back?

This might be because when the mysql instance is bound, we generate ssl certs for the instance and return them to the app, but the instance itself still has to update with those ssl certs and that can take awhile. We used to have the bind operation wait for the instance to finish updating with the certs, but then binds were timing out fairly frequently.

**Comment by Pivotal-Jayson-Hairston** [comment]
@mkjelland Yes, this happens consistently. Not only on my foundation but this has happened on another totally different pcf foundation as well. The root is really the first error that does not provide a useful error, just the general 502.

**Comment by mkjelland** [comment]
@Pivotal-Jayson-Hairston what version of pcf are you using? Can you try running the bind with CF_TRACE to see if there is any additional information in the response?

**Comment by Pivotal-Jayson-Hairston** [comment]
As discussed, I've sent the verbose cf trace through Slack DM.

**Comment by Pivotal-Jayson-Hairston** [comment]
I have increased the http/https load balancer timeout from 30 seconds to 60 seconds within the GCP console. The binding operation is now able to bind! Now the binding operation is taking 32 seconds to complete.

Thank you for you're help, this is not really an issue with the GCP broker but with the timing of the `cf bind-service` operation in combination with the timing of the creation of the proper 2nd generation cloud SQL(mysql) resources within the GCP Project configured.

**Comment by mkjelland** [comment]
For anyone else hitting this issue, I recommend setting the load balancer timeout to 60 seconds, which is the cloud foundry default timeout for bind operations.

**Comment by ronakbanka** [comment]
@mkjelland Can you point to the docs link.

**Comment by mkjelland** [comment]
@ronakbanka Sorry, which docs do you mean?
