### ISSUE TITLE
Support Google Cloud CDN

### ISSUE THREAD

**Issue by madmod** [GoogleCloudPlatform/gcp-service-broker#205]
Setting up a GCS bucket and fronting it with Google Cloud CDN is a common use case for developers. By adding this feature it would allow developers to self serve creation of a modern web app without external tools like Terraform or Ansible.

**Comment by bhouston** [comment]
This is a big one.  Nearly every production service needs to use Google Cloud CDN in front of Google Cloud Storage or in front of select APIs.
