### ISSUE TITLE
Is there a service broker for Red Hat OpenShift?

### ISSUE THREAD

**Issue by alberttwong** [GoogleCloudPlatform/gcp-service-broker#236]

**Comment by josephlewis42** [comment]
Hi Albert,

If you're looking at installing this broker in OpenShift Kubernetes, I know some other folks were doing something similar in #165. This service broker should work with a minor tweak (there's a fix in the pipeline for it too with v4.0.0).

There's also https://github.com/GoogleCloudPlatform/k8s-service-catalog which uses the hosted GCP Service Broker, but it doesn't support as many services as this one.

Cheers!
\- Joseph
