### ISSUE TITLE
Don't require service prefixes for iam roles

### ISSUE THREAD

**Issue by ccemeraldeyes** [GoogleCloudPlatform/gcp-service-broker#24]
e.g. instead of storage.admin, just accept admin for a storage service binding

**Comment by josephlewis42** [comment]
Marking this one as wontfix because of the amount of work we'd need to do to make it reverse compatible.

Some roles, like `admin` are valid by themselves and as a secondary part of `storage.admin`, it's not clear how we'd disambiguate, especially when users can create custom roles.
