### ISSUE TITLE
4.0 Countdown

### ISSUE THREAD

**Issue by josephlewis42** [GoogleCloudPlatform/gcp-service-broker#240]
Ideally the 4.0 release will leave users with a good impression and not in a place where they can't get back.

Here are a few of the remaining papercuts that need to be closed out before a successful release:

- [x] Remove the DB migration that DROPs custom plan details. The number should still remain in case anyone built/installed their own version of the broker but it should be a noop. This will ensure it's safe moving forward.
- [x] Ensure custom plans get parsed correctly, there was a plan to move them to nested options you could configure in the PCF tile but support was lacking in the forms and the upgrade path wasn't very clear, instead we need to implement custom logic to parse those options back out.
- [x] Upgrade the Concourse pipeline to work with the new broker

**Testing**

- [x] Install the new broker with the instructions in the README.md file
- [x] Test an upgrade from the old system with every service type provisioned to the new, taking a snapshot of the DB before and after.
- [x] Try creating custom plans in the old system and ensure they still continue working in the new.

**Other**

- [ ] Ensure the new tile passes building against Pivotal's system
- [x] Re-generate OSDF-3.6.0.txt and document how to do it
- [x] Upgrade the release notes
- [x] Match Changelog format to https://keepachangelog.com/en/1.0.0/#how
- [x] Document the release process in the `docs/` directory

**Comment by aeckard87** [comment]
What's the ETA?

**Comment by josephlewis42** [comment]
Hi @aeckard87,

We're in the process of testing the 4.0 tile right now, there's a problem where the tile deploys but fails to register so we're investigating it but once that's done I'll upload a `.pivotal` file in the releases section and start the process of getting it updated on PivNet.

Tagging @evandbrown on this too.

**Comment by aeckard87** [comment]
Thanks @josephlewis42!

Is this only being tested for 2.2.X?

**Comment by josephlewis42** [comment]
Hi @aeckard87,

I am currently testing on 2.2.X, but from my understanding Pivotal will build and run the tile against the supported versions of PCF before it gets pushed to PivNet. I'm meeting with some people next week from Pivotal to talk about the depth of testing that gets done. Let me know if there's anything in particular you're interested in.

In the meantime we've been looking into the failure to register and it looks like it's an upstream issue in the PCF tile builder which they're getting ironed out.

**Comment by josephlewis42** [comment]
@aeckard87, just to give you an update on this. We have an RC tile on PivNet that's passing instillation checks v2.0 to v2.3.

However, there's a breaking change in 4.0 where we're now specifying plan IDs for built-in plans rather than auto-generating them at install time. Long-term this is going to help us improve velocity and support, but it means people doing upgrades will need to upgrade their instances from the legacy plans to the modern ones.

I've written a compatibility layer that you can enable via the tile or environment variable that will help you migrate cleanly. You can see the work in #281 I'm doing testing this week to make sure the layer works for all our services.

**Comment by josephlewis42** [comment]
@aeckard87 version 4.0 is released.

Note: if you're upgrading from 3.x, follow the [upgrading docs](https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/master/docs/upgrading.md) to ensure your plans continue to work. Specifically, you'll need to enable compatibility mode before upgrading or else the upgrade will fail. This will notify your users to upgrade to supported plans when they try to modify/bind to existing plans with old IDs.
