### ISSUE TITLE
Support secretName in CloudSQL binding

### ISSUE THREAD

**Issue by barrywark** [GoogleCloudPlatform/gcp-service-broker#258]
When creating a `cloud-sql-mysql/beta` binding, I would like to be able to specify the secret name that is created for the connection credentials. Currently, the binding name is used as the secret name. 

The IAM service account binding (`cloud-iam-service-account/beta`) allows a `secretName` in the spec to specify the desired secret name.

**Comment by josephlewis42** [comment]
Hi Barry,

Based on the binding name, I think you might be looking looking for the [k8s-service-catalog](https://github.com/GoogleCloudPlatform/k8s-service-catalog). This service broker was originally built for cloud foundry instillations, although we have had some people investigate using it in k8s.

Cheers!
\- Joseph
