### ISSUE TITLE
Add the ability to bind to existing "Multi-Regional" deployed assests from another foundation

### ISSUE THREAD

**Issue by tehkuhnz** [GoogleCloudPlatform/gcp-service-broker#262]
As a platform operator, I would like to see the service broker bind to existing multi-regional assets that are already created from another foundation/service broker in a different region. This would allow for multi-regional design from a PCF platform perspective, without having to worry about orchestrating the out of platform assets/resoruces.

Please see an example of this with the Azure Service Broker:
https://dzone.com/articles/pcf-spring-boot-applications-using-azure-sql-part

**Comment by evandbrown** [comment]
Hey Nick, do you have an idea of which services would be most important to support in this fashion? When you bind an existing service, do you like the approach where there are service plans specifically for existing services (e.g., `ExistingPubSubTopic`)?

**Comment by josephlewis42** [comment]
closing due to age
