### ISSUE TITLE
Add service which generates API keys

### ISSUE THREAD

**Issue by mattysweeps** [GoogleCloudPlatform/gcp-service-broker#278]
It would be convenient if there was a service offering for an API Key generator.

Provisioning a service would be the creation of a new API key by name. Name could be randomly generated with a GCP broker prefix, or something similar.
```
{
  "name": "my-api-key"
}
```

Binding to the service would be a no-op; all that is needed is the API key to exist in the `VCAP_SERVICES` environment variable.
```
VCAP_SERVICES=
{
  "my-api-key": [
    {
      etc....
      "credentials": {
        "key": "...key-contents..."
      }
    }
  ],
}
```

I don't know if a more general-purpose `Credentials Service` makes more sense, since API Keys are under the Credentials view in the GCP cloud console.

**Comment by josephlewis42** [comment]
Closing this until GCP supports this feature
