### ISSUE TITLE
Sample VCAP_SERVICES JSON for google-datastore 

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcp-service-broker#290]
The question came up here: https://github.com/spring-cloud/spring-cloud-gcp/issues/1068

Please advise. Thanks!

**Comment by meltsufin** [comment]
What's `instance_name` here? Datastore doesn't have such a concept AFAIK. It does have a namespace concept, which would be nice to have here.

**Comment by josephlewis42** [comment]
`instance_name` is what the user named the datastore in PCF when they created it through the CLI.

I've created a backlog item to add a namespace param to the provision request that'll get explicitly passed along: #291
