### ISSUE TITLE
Support for CloudSQL Private IP for the GCP Service Broker.

### ISSUE THREAD

**Issue by abutnare** [GoogleCloudPlatform/gcp-service-broker#293]
Joint Pivotal-Google Cloud Customers are keen to access GCP serices privately.
CloudSQL has added access for Private IP, the ask is to make this available via the GCP service broker.
https://cloud.google.com/sql/docs/mysql/configure-private-ip

Many thanks!

**Comment by marcohelmerich** [comment]
I would like to second this request. Our Developers would like to keep dependencies in their application for cloud databases and local testing (e.g. postgres in docker on laptop) the same. Thats not possible with public CloudSQL and the needed dependencies (sql proxy etc.). Private IP would solve this issue

**Comment by stwomack** [comment]
Another request for this. Healthcare customers do not want to expose their DBs to public IPs, by policy. They want to use GCP Cloud-SQL, but cannot without this feature.
