### ISSUE TITLE
Build and Release Docker Images

### ISSUE THREAD

**Issue by josephlewis42** [GoogleCloudPlatform/gcp-service-broker#349]
As part of our 4.2.0 push, we need to build and push Docker images that the GCP Service Broker can be released into.

- [x] Create a docker image that contains the gcp-service-broker
- [ ] Modify the pipeline to build it
- [ ] Release them to gcr.io
- [ ] Modify the tile to use it rather than a buildpack
- [ ] Write docs for how to use the Docker image with k8s.

**Comment by josephlewis42** [comment]
@craigatgoogle bumping this to the backlog since this was changed with the release of brokerpaks as a separate entity.

If you find a customer that really needs it I can prioritize it.

**Comment by craigatgoogle** [comment]
Sounds good. I think we'll have some more bandwidth for this in Q1.
