### ISSUE TITLE
Support Firebase Authentication as Service Broker

### ISSUE THREAD

**Issue by bhouston** [GoogleCloudPlatform/gcp-service-broker#359]
I understand the main way Google Cloud Platform suggests doing Auth as a service (AaaS) is via Firebase Authentication (https://firebase.google.com/docs/auth/ ).

As such as we choosing Firebase Auth for our AaaS.  We would like to be able to provision and configure it via Service Brokers if that was possible.

Maybe for some reason it isn't recommended to configure it in this way?

BTW this the whole Service Brokers approach is an amazing initiative.  I love it.  And we are trying to embrace it fully (which maybe a bit premature I worry....)

**Comment by josephlewis42** [comment]
Hi @bhouston I've created a ticket with the Terraform team to support Firebase because I know you're moving forward with that product: https://github.com/terraform-providers/terraform-provider-google/issues/2973
