### ISSUE TITLE
Missing titles for properties and enum values in JSON schema for Service Plans

### ISSUE THREAD

**Issue by pkosiec** [GoogleCloudPlatform/gcp-service-broker#384]
**Description**

In some JSON schemas for Service Plans, there are properties without `title` property. Also, in enums there are no labels for values, which can be achieved in JSON schema with `oneOf`.

**Reasons**

The `title` property is widely used by JSON schema form rendering libraries as a field label. The suggested change, as well as introducing friendly, human-readable labels for enums, will greatly improve usability on UI.

**Examples**

Let's take as an example the "Beta" plan for "Cloud SQL - MySQL" Service Class. As you can see on the screenshot, some properties have `title` specified, some don't - and, in a result, they fallback to `camelCase` properties names:

![screen shot 2018-12-14 at 15 35 22](https://user-images.githubusercontent.com/7155799/50010498-ede46100-ffb9-11e8-8ebb-d32c1dc92f21.png)

Here's an example of enum value without label:

![screen shot 2018-12-14 at 15 36 42](https://user-images.githubusercontent.com/7155799/50010500-f0df5180-ffb9-11e8-8404-070c2dd9ad76.png)

---

**Expected result**

This is how the form based on JSON schema renders when all properties have title specified (as an example: Azure SQL Database 12.0 plans from https://github.com/Azure/open-service-broker-azure):

![49998247-15283780-ff94-11e8-9ece-ffb15d5ab3d0](https://user-images.githubusercontent.com/7155799/50010987-25074200-ffbb-11e8-856b-6eca6789aad0.png)

**Comment by josephlewis42** [comment]
Hi @pkosiec, 

This repository is for the open source service broker, mainly used in Cloud Foundry installations whereas I think you wanted the hosted service broker. I filed a bug with that team including all the details you have here b/122068855.

In the meantime, if you ever wanted to try the open source service broker, I added support for JSONSchema and labels here: https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/392

Cheers!
- Joseph

**Comment by pkosiec** [comment]
Hi @josephlewis42,
I wanted to report this bug for the open source service broker. I use register it in the Service Catalog on Kubernetes. So this is a good place for that, right?

I just wanted to point out that some of Service Plans' schemas have the titles missing for some fields. And also, a nice enum value display label would be a great usability improvement.

Cheers!
