### ISSUE TITLE
Service broker should create its own database

### ISSUE THREAD

**Issue by mdcarlson** [GoogleCloudPlatform/gcp-service-broker#40]
For a better user experience, it would be helpful if the GCP service broker tile could leverage metadata to determine whether the PCF MySQL tile is installed and, if so, automatically create the servicebroker database, user and permission grants.

I believe that Pivotal's Spring Cloud Services tile checks for presence of MySQL and RabbitMQ and uses them, if present.

**Comment by markdcunha** [comment]
To clarify the use cases:
1. On-prem customer wants to use GCP and they have Pivotal MySQL. Allow them to enter the Plan type and name and check/auto-create the database
2. GCP customer wants to use GCP and selects Cloud SQL, allow them to pick the name and check/auto-create the database

**Comment by josephlewis42** [comment]
The broker supports binding a database via `VCAP_SERVICES`, but we won't go create a database because it's too difficult to come up with a correct backup/restore solution with that scenario.
