### ISSUE TITLE
Why does GCP Service Broker need OWNER role?

### ISSUE THREAD

**Issue by aeckard87** [GoogleCloudPlatform/gcp-service-broker#400]
What permissions does the service account actually need that OWNER has. It would be nice to know if we could utilize editor role instead.

**Comment by josephlewis42** [comment]
Hi @aeckard87,

The service broker needs to be able to use the `*.setIamPolicy` permissions on the resources it creates which the editor doesn't have `diff <(gcloud iam roles describe roles/editor) <(gcloud iam roles describe roles/owner)`.

You could create a custom role that had the `*.setIamPolicy` permissions on it or maybe use [IAM Conditions](https://cloud.google.com/iam/docs/conditions-overview) to limit the accounts ability to access things it shouldn't.

Cheers!
\- Joseph
