### ISSUE TITLE
CloudSQL Services not available after "successful" install

### ISSUE THREAD

**Issue by mdcarlson** [GoogleCloudPlatform/gcp-service-broker#41]
We installed beta 2.0.0 of the GCP service broker earlier this week into PCF 1.8.6 on vSphere.

After a couple of failed attempts due to misconfiguration of database certs/keys, the installation succeeded (no errors).

`cf marketplace` listed the expected GCP services except for CloudSQL.

Repeating this test this afternoon after rebuilding this PCF instance in our lab, we found similar results.

The output of `cf marketplace` is: 
```
service           plans                                      description
    google-bigquery   default                                    A fast, economical and fully managed data warehouse for large-scale data analytics
    google-ml-apis    default                                    Machine Learning Apis including Vision, Translate, Speech, and Natural Language
    google-pubsub     default                                    A global service for real-time and reliable messaging and streaming data
    google-storage    standard, nearline, reduced_availability   A Powerful, Simple and Cost Effective Object Storage Service
    p-mysql           100mb                                      MySQL databases on demand
```

The output of a sample `cf create-service google-cloudsql` command is:

```
cf create-service google-cloudsql d4_standard mycloudsql -c '{"instance_name": "myinstance", "database_name": "mydb"}'
Creating service instance mycloudsql in org gcp-service-broker-org / space gcp-service-broker-space as mcarlson...
    FAILED
    Service offering google-cloudsql not found
```

**Comment by ccemeraldeyes** [comment]
Were any cloudsql custom plans created? If not, it's in adherence to the service broker api that cloudsql not appear in the service list.

**Comment by mdcarlson** [comment]
Colleen,

Thanks for the reply.  In the [Pivotal Network documentation for the GCP Service Broker "tile"],(http://docs.pivotal.io/gcp-sb/using.html#cloudsql) the first step in the "Using GCP Service Broker" section under CloudSQL is:

```Run cf create-service google-cloudsql to create a new database instance and database. PCF Operators create custom plans for Google Cloud SQL when installing the GCP Service Broker. ```

I see now that that I missed the optional configuration step in the tile setup that is used to create custom CloudSQL plans.  

Improvement ideas:

- Update the docs in the CloudSQL section of the "Using" documentation to clarify that this optional plan creation step is a prerequisite for use
- Either pre-populate the CloudSQL tier names in the plan configuration or to provide an example or two.   I read the docs at the [provided link](https://cloud.google.com/sql/pricing), but am not quite sure that I got it right.
- Validate that a valid tier name was provided when the user saves the configuration information for the CloudSQL plan.  I think that current approach requires that I wait until the end of an "apply changes" run to find out if I supplied a valid tier name.  In large installations, this wait time could be over an hour (especially if someone forgot to uncheck errands/smoke tests like I just did). ;-)

Thanks for the help!

Mark

**Comment by mdcarlson** [comment]
I used the tile configuration to define two custom plans called "small-d0-standard" and "medium-d4-standard".   I clicked apply changes in OpsMan and the deploy was "successful".

However, `cf marketplace` still does not show the plans as being available.  

The changelog for this apply changes run is [here](https://gist.github.com/mdcarlson/0a566fb70f06be881ac229d5bac17d35).  I do not see any errors or warning messages.

With  a task duration of 1 second, it doesn't appear that the configuration changes were detected.

Screenshot showing two custom CloudSQL plans:
![gcp-service-broker-cloudsql-plan-config-01](https://cloud.githubusercontent.com/assets/253412/19619701/a226eb28-982a-11e6-9e2c-9f8574402674.png)

Screenshot showing details of `small-s0-standard` plan:
![gcp-service-broker-cloudsql-plan-config-02](https://cloud.githubusercontent.com/assets/253412/19619702/a6351a8c-982a-11e6-902c-9be60a3b77cc.png)

**Comment by mdcarlson** [comment]
Uninstalling and re-installing the tile, this time defining my two custom plans during the initial deploy, successfully created the plans.  The plans appear in the results of the `cf marketplace` command.

Creating a new plan `large-d8-standard` and applying changes worked as expected.

I'll delete the tile again and reinstall without configuring custom CloudSQL plans to see if I can recreate the issue.
