### ISSUE TITLE
"Provided plan does not exist record not found" error attempting to create google-cloudsql service

### ISSUE THREAD

**Issue by mdcarlson** [GoogleCloudPlatform/gcp-service-broker#42]
Newly re-installed GCP service broker 2.0.0 tile on PCF 1.8.6 on vSphere.

Tile initially installed without custom CloudSQL plans.  A subsequent deploy was used to add one custom plan `small-d0-standard`.  This plan appears in both `cf marketplace` output as well as in AppsManager.

However, attempt to create a new cloudsql service fail with `Provided plan does not exist record not found` errors.

**Command issued:**
` cf create-service google-cloudsql small-d0-standard dev-small-mysql -c '{"instance_name": "dev-small-mysql-01", "database_name": "mydb"}'`

**Result:**
`FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: The provided plan does not exist record not found
` 

As you would expect, this behavior is also seen when attempting to create the service from AppsManager (yes, I know AppsMan can't really create async services).

![gcp-service-broker-appsman-error-01](https://cloud.githubusercontent.com/assets/253412/19620454/037dee52-983b-11e6-86a3-bea3e970f42a.png)

**Comment by mdcarlson** [comment]
I suspect that some of the plan records are not getting cleaned up when the tile is deleted.   

The gist below points to a mysqldump file from our "servicebroker" database.

https://gist.github.com/mdcarlson/8bd4f59eb90fcb6ffd2cbb15e18072ed

Mark

**Comment by mdcarlson** [comment]
Dropping and recreating the `servicebroker` db appears to be a workaround to this issue.   The error no longer occurs when attempting to create a service from a plan listed in the `cf marketplace` results.

**Comment by ccemeraldeyes** [comment]
Should be fixed by #33 and #2 , both of which are in progress.
