### ISSUE TITLE
Support multiple projects

### ISSUE THREAD

**Issue by josephlewis42** [GoogleCloudPlatform/gcp-service-broker#446]
The service broker should support provisioning into multiple projects based on rules.

It will do this by letting operators enter a policy to change Terraform environment variables based on labels.

- [x] Expand labels to support more options
- [ ] Add a form for entering a policy
- [ ] Add documentation for the policy
- [ ] Add HIL functions to get an environment variable and coalesce multiple together.
- [ ] Pass these environment variables to TF when it's called.

**Comment by shinmyung0** [comment]
What is the roadmap look like for this? We are running into issues using the gcp service broker for services like Firestore which has a limitation to create only 1 instance per project.

**Comment by josephlewis42** [comment]
Closing this out due to lack of capacity.
