### ISSUE TITLE
Cloud SQL custom plan not being created

### ISSUE THREAD

**Issue by openday555** [GoogleCloudPlatform/gcp-service-broker#462]
PCF service broker tile, under generate custom plans for Google CloudSQL MySQL I created a custom plan, and applied changes. The plan I created does not show in market place, yet there are no errors being reported in logs. The following output shows the custom plan with guid.
`CLOUDSQL_MYSQL_CUSTOM_PLANS {"plan-100":{"description":"plan-100","display_name":"plan-100","guid":"43f981b5-5256-450d-a400-af810558e869","max_disk_size":"100","name":"plan-100","pricing_plan":"PER_USE","service":"4bc59b9a-8520-409f-85da-1c7552315863","tier":"db-n1-standard-2"}}` 

Creating  a service instance using plan **db-n1-standard-2** from within cf cli or Ops Manager UI with the following parameters `cf create-service google-cloudsql-mysql mysql-db-n1-standard-2 custom -c '{"disk_size":"100","auto_resize":"true"}` gets created successfully.

**Comment by josephlewis42** [comment]
Hi @openday555,

To help troubleshooting would you mind telling me the version of the broker you're using?

Based on what you pasted it seems like you updated the form in OpsMan to add `plan-100` then applied changes through OpsMan and copied that log line out, is that correct?

If the install went through without errors my guess is that there was an issue on the Cloud Controller side when it tried to fetch the refreshed catalog from the broker. I'm currently upgrading my PCF installation to better help figure out what's going on.

Also, would you mind double checking the output of `cf service-access` to make sure the plan doesn't show up there? Another reason it might not be showing up in the marketplace is if the plan was created but not yet enabled for users.

Thanks!
\- Joseph

**Comment by openday555** [comment]
Thank you. GCP Service broker "version": "4.2.2"
"_Based on what you pasted it seems like you updated the form in OpsMan to add plan-100 then applied changes through OpsMan and copied that log line out, is that correct?_" Yes this is correct.

The output from `cf service-access` does not list the custom plan. Thank again.
