### ISSUE TITLE
Force delete bucket during a `cloud-storage` ServiceInstance deprovision

### ISSUE THREAD

**Issue by vpasquier** [GoogleCloudPlatform/gcp-service-broker#464]
Hello,

I was wondering if there were an existing strategy to force delete bucket (empty or Not) when de-provisioning a Service Instance `cloud-storage`:

The goal would be to automatize this force deletion (and not manually create/apply a cleaner job).

- Would it be interesting at thend for people to update the deletion policy here? https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/master/pkg/providers/builtin/storage/broker.go#L83
- If not (or too risky), what would you recommend (like having some hooks or any way to empty the bucket before the service instance deletes the bucket)

Thank you

**Comment by josephlewis42** [comment]
Hi @vpasquier,

The GCS API only supports deleting empty buckets, but I can understand the desire. Unfortunately, we're kind of constrained by the service broker API as to what parameters we can take during different points of the lifecycle.

What do you think about a bucket taking an additional parameter `force_delete` at create time that would set a label on a bucket. At deletion time if the label was set then the service-broker would iterate over the items in the bucket and delete each one before deleting the bucket?

You could manually set the label on applicable buckets that currently exist.

If you have other times where you think webhooks would be a good idea I'd definitely be interested.

Cheers!
- Joseph

**Comment by vpasquier** [comment]
Hey!

We are not very familiar with the labels but we like the idea definitely!

Related to hooks, we will keep you in touch if we are using them meanwhile (with Helm 2... but we are not very convinced that's the best idea)

We really appreciate!

**Comment by vpasquier** [comment]
Hey! @josephlewis42 

We just notice that our bucket is not deprovisioned by the ServiceInstance :) Did you make any change ? cause we didn't modify our resource.

In all cases, it's super cool thanks!
