### ISSUE TITLE
gcp-service-broker-4.2.3 tile failed in Pivotal PAS 2.4.13 and 2.59 due to go version 1.10 is deprcated 

### ISSUE THREAD

**Issue by andy0301** [GoogleCloudPlatform/gcp-service-broker#514]
Hello,

We are using PCF on Google cloud platform and using gcp-service-broker tile version is 4.2.3, but recently when we are upgrading both PAS version to 2.4.13 and 2.5.9, gcp-service-broker tile failed because the tile using go version is 1.10, but in PAS 2.4.13 and 2.5.9 go-offline-buildpack upgraded to 1.8.42 which is already deprecated go 1.10...I found in master branch https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/master/manifest.yml#L25  seems already fix this issue, but seems there is no new release for it. So could you please help release this fix as soon as possible? Because we are really blocking by this issue for our auto-upgrade.

Thanks
Andy Cai
CloudOps, StubHub

**Comment by shinmyung0** [comment]
It would be great if we could get an ETA on the next release, as we have some other issues blocked on this. If it's too far out, we will have to come up with some mitigation plans on our end.

**Comment by josephlewis42** [comment]
I'm going to make a PR to get our current helm chart cherrypicked from develop to master then we'll start the tile release process

**Comment by evandbrown** [comment]
Release work is being tracked in #517
