### ISSUE TITLE
Memorystore not showing up in GCP broker?

### ISSUE THREAD

**Issue by shinmyung0** [GoogleCloudPlatform/gcp-service-broker#539]
I saw this issue #467 as closed, but am not seeing the memory store service showing up in the marketplace. We are already on the latest version of the Broker released as a tile and have preview services enabled. Is there something additional we have to do to enable memorystore?

**Comment by dominikmueller** [comment]
Are you using the version from the Pivotal Network or do you build the tile by yourself?

The latest available version in the PivNet is v4.3.0 which afaik does not include Redis/Memorystore.
If you look at the tag v4.3.0, you can see that Redis is commented out ([relevant code line](https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/v4.3.0/pkg/providers/builtin/registry.go#L57)).

This means that you either have to wait for v4.4.0 to be released (#538) or you need to build it yourself.
You can use the concourse pipelines in the `ci` folder as a reference on how to build the tile.

**Comment by josephlewis42** [comment]
There's also a pre-release here: https://github.com/GoogleCloudPlatform/gcp-service-broker/releases

I'll check in with the Pivotal folks to see why it hasn't been pushed to PivNet yet.

**Comment by shinmyung0** [comment]
Okay that's good to know, thank you!
