### ISSUE TITLE
Release 5.0.0 incompatible with PAS 2.7

### ISSUE THREAD

**Issue by scobrown-sh** [GoogleCloudPlatform/gcp-service-broker#549]
In 2.7 interface there is no option for cloudsql_postgres_custom_plans_0/service.  With 2.6 this is a drop down which is used to select "Google CloudSQL for PostgreSQL".  

Using concourse to deploy gcp service broker 5.0.0 on 2.7 I get the following error WITH cloudsql_postgres_custom_plans_0/service present

{"errors":{".properties.cloudsql_postgres_custom_plans":["Record 1: service Non-configurable properties cannot be configured."]}}

Using concourse to deploy gcp service broker 5.0.0 on 2.7 I get the following error WITHOUT cloudsql_postgres_custom_plans_0/service present

- Expected to find variables:
    - cloudsql_postgres_custom_plans_0/service

Please help to resolve this issue so we can deploy GCP Service Broker on Pivotal Cloud Foundry with OpsMan / PAS 2.7.3

**Comment by josephlewis42** [comment]
It looks to me like the field is still in the `tile.yaml` file, I suspect OpsMan may have changed to no longer allow setting select fields with a single value. If you don't include service, does the plan continue to show up in the broker? If so, I'd recommend removing it from your configuration and continuing that way.

**Comment by josephlewis42** [comment]
Update: whoops, didn't mean to close this.

I'm flipping around some field values trying to make the field configurable in a way that the OpsMan UI won't outright reject the tile. Currently at attempt 2.

Pivotal's tile generator still seems to have issues validating whether or not things will work ahead of time: https://github.com/cf-platform-eng/tile-generator/issues/281

**Comment by josephlewis42** [comment]
I've uploaded a possible fix as 5.0.1: https://github.com/GoogleCloudPlatform/gcp-service-broker/releases/tag/v5.0.1

The tile will still report to be 5.0.0 when installing. If it works, I can bump the version and start the release process to get it pushed to PivNet
