### ISSUE TITLE
Open up Google Group for public access

### ISSUE THREAD

**Issue by mogul** [GoogleCloudPlatform/gcp-service-broker#554]
From the README:
> Subscribe to the [gcp-service-broker Google group](https://groups.google.com/forum/#!forum/gcp-service-broker) for discussions and updates.

However, the group appears to be closed off for public access:

![image](https://user-images.githubusercontent.com/47762/75469767-6a0b6000-5944-11ea-8cab-88f4506a0856.png)

Can you open it up?

**Comment by josephlewis42** [comment]
Hi @mogul, 

The best place to watch for updates and send messages is actually in GitHub. I've updated the README to reflect that.
