### ISSUE TITLE
Default to minimum necessary permissions on bind

### ISSUE THREAD

**Issue by ccemeraldeyes** [GoogleCloudPlatform/gcp-service-broker#9]
Use curated roles as much as possible, defaulting to a viewer-type role.

**Comment by mgoddard-pivotal** [comment]
I'm not sure if this is the spirit of this issue, but having a reasonable default for the values passed in on binding of the service seems like a great idea.  For example, if you commonly bind PubSub with the following, how about making that the default:

  `cf bs app_name service_instance_name -c '{"role": "pubsub.admin" }'`

For Spring Cloud Dataflow applications, where this binding happens in the code, it would be handy to not need to know the service-specific JSON snippet to pass in.
