### ISSUE TITLE
document example use of service account credentials

### ISSUE THREAD

**Issue by ccemeraldeyes** [GoogleCloudPlatform/gcp-service-broker#95]
It is not clear to new users that the PrivateKeyData supplied on bind may need to be base64 decoded to be used. Document this and provide examples.

**Comment by SunIn312** [comment]
@ccemeraldeyes , thanks for your support to open this ticket.

the documentation provided on https://docs.pivotal.io/gcp-sb/using.html#pubsub link, none where clearly mention while gcp pubsub broker instance created from pivotal, what are the information's are populated inside VCAP variables, what there usages & in which format. the key names used in side pivotal VCAP variables are completely different than the key names gcp pub sub api (either service account credential/user account credentials) expected while used to created subscription. The current document need to be enhanced with running examples. 

Can this be taken on priority.

**Comment by ccemeraldeyes** [comment]
Closed via https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/112
