### ISSUE TITLE
Configure defaults for provisioning request parameters

### ISSUE THREAD

**Issue by claudio-benfatto** [GoogleCloudPlatform/gcp-service-broker#98]
Hello,

first of all thanks for developing this project!

Our use case is the following:

we have most of our infrastructure deployed in the `eu-west` region and we would like to set the default provisioning parameters for some of the resources (for example `google-storage` and `google-cloudsql`) accordingly and at deployment time. 
Mainly, so that our users could be spared from setting those parameters which each request ie. 

```
cf create-service google-storage standard test-bucket-eu -c '{"location": "eu"}'`
 ```

what would be really nice in my opinion is to add the capability of overriding those hard-coded default values passing in the manifest some optional json (or any other format) configuration, ie.:

```
GOOGLE_STORAGE_PROVISIONING_DEFAULTS: '{"location": "eu"}'
```

Let me know what you think about this proposal... or maybe if there is already a way to do it, that perhaps I overlooked!

Thanks,
Claudio

**Comment by ccemeraldeyes** [comment]
Great idea! I'll get this prioritized. Sorry for the late response!

**Comment by claudio-benfatto** [comment]
Great! Thanks @ccemeraldeyes !

**Comment by mgoddard-pivotal** [comment]
This same approach could be used to help make binding to the service instance simpler.  For example, if we envision doing this routinely:

  `cf bind-service myapp foobar -c '{"role": "pubsub.admin"}'`

then having this type of configuration available would simplify the binding:

  `GOOGLE_STORAGE_BINDING_DEFAULTS: '{"role": "pubsub.admin"}'`

**Comment by ccemeraldeyes** [comment]
proposal:

* new table ServiceDefaults (Id, ServiceId, Type, Key, Value) - where Type = "provision" or "bind"
* new env variables GOOGLE_<service name>_DEFAULTS for each service

`GOOGLE_STORAGE_DEFAULTS: '[
        {"type": "provision", "key": "location", "value": "eu"},
        {"type": "bind", "key": "role", "value": "storage.admin"}
]'`
* new tile pages for each service (probably combine with #51 ) with dropdown prefilled with provision or bind, dropdown prefilled with available settings, and textbox for value

@claudio-benfatto @mgoddard-pivotal if this seems reasonable I'll start this today

**Comment by mgoddard-pivotal** [comment]
Yes, @ccemeraldeyes, that would work nicely, I think.

**Comment by ccemeraldeyes** [comment]
fyi this feature is in progress, on hold while a significant code refactor happens. Hopefully will resume work next week.
